export const products = [
  {
    id: 1,
    name: "Hortelã",
    price: 70.9,
    isPromotion: false,
    ratings: 24,
    stars: 4.5,
    discount: 0,
    img: "assets/toothpaste.png",
    type: "toothpaste",
  },
  {
    id: 2,
    name: "Morango",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/toothpaste.png",
    type: "toothpaste",
  },
  {
    id: 3,
    name: "Uva",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/toothpaste.png",
    type: "toothpaste",
  },
  {
    id: 4,
    name: "Café",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/toothpaste.png",
    type: "toothpaste",
  },
  {
    id: 5,
    name: "Bamboo",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/toothbrush.png",
    type: "toothbrush",
  },
  {
    id: 6,
    name: "Mógno",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/toothbrush.png",
    type: "toothbrush",
  },
  {
    id: 7,
    name: "Carvalho",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/toothbrush.png",
    type: "toothbrush",
  },
  {
    id: 8,
    name: "Fio dental",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/dental-floss.png",
    type: "dental-floss",
  },
  {
    id: 9,
    name: "Fio dental",
    price: 70.9,
    isPromotion: true,
    ratings: 24,
    stars: 4.5,
    discount: 20,
    img: "assets/dental-floss.png",
    type: "dental-floss",
  },
];
